// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FactoryCisum",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        .library(
            name: "FactoryCisum",
            targets: ["FactoryCisum"]
        ),
    ],
    dependencies: [
        .package(name: "CisumKernel", path: "../CisumKernel"),
        .package(name: "CisumUIComponents", path: "../CisumUIComponents"),
        .package(name: "MagicKit", path: "../MagicKit"),
        .package(name: "MagicPlayMan", path: "../MagicPlayMan"),
        .package(name: "ProviderCloud", path: "../ProviderCloud"),
        .package(name: "ProviderContentView", path: "../ProviderContentView"),
        .package(name: "ProviderControlView", path: "../ProviderControlView"),
        .package(name: "ProviderDevice", path: "../ProviderDevice"),
        .package(name: "ProviderPlayback", path: "../ProviderPlayback"),
        .package(name: "ProviderPlugin", path: "../ProviderPlugin"),
        .package(name: "ProviderRootView", path: "../ProviderRootView"),
        .package(name: "ProviderScene", path: "../ProviderScene"),
        .package(name: "ProviderSettings", path: "../ProviderSettings"),
        .package(name: "ProviderToolbar", path: "../ProviderToolbar"),
        // MARK: - Plugin Dependencies (直接由 Factory 装配)
        .package(name: "PluginAudio", path: "../PluginAudio"),
        .package(name: "PluginAudioControl", path: "../PluginAudioControl"),
        .package(name: "PluginAudioCopy", path: "../PluginAudioCopy"),
        .package(name: "PluginAudioDBView", path: "../PluginAudioDBView"),
        .package(name: "PluginAudioDemo", path: "../PluginAudioDemo"),
        .package(name: "PluginAudioDownload", path: "../PluginAudioDownload"),
        .package(name: "PluginAudioJob", path: "../PluginAudioJob"),
        .package(name: "PluginAudioLike", path: "../PluginAudioLike"),
        .package(name: "PluginAudioPlayMode", path: "../PluginAudioPlayMode"),
        .package(name: "PluginAudioProgress", path: "../PluginAudioProgress"),
        .package(name: "PluginAudioScene", path: "../PluginAudioScene"),
        .package(name: "PluginAudioSettings", path: "../PluginAudioSettings"),
        .package(name: "PluginAudioWidgetControl", path: "../PluginAudioWidgetControl"),
        .package(name: "PluginBook", path: "../PluginBook"),
        .package(name: "PluginBookControl", path: "../PluginBookControl"),
        .package(name: "PluginBookDBView", path: "../PluginBookDBView"),
        .package(name: "PluginBookLike", path: "../PluginBookLike"),
        .package(name: "PluginBookPlayMode", path: "../PluginBookPlayMode"),
        .package(name: "PluginBookProgress", path: "../PluginBookProgress"),
        .package(name: "PluginBookScene", path: "../PluginBookScene"),
        .package(name: "PluginBookSettings", path: "../PluginBookSettings"),
        .package(name: "PluginFileLog", path: "../PluginFileLog"),
        .package(name: "PluginLikeButton", path: "../PluginLikeButton"),
        .package(name: "PluginOpenButton", path: "../PluginOpenButton"),
        .package(name: "PluginPluginManager", path: "../PluginPluginManager"),
        .package(name: "PluginReset", path: "../PluginReset"),
        .package(name: "PluginScene", path: "../PluginScene"),
        .package(name: "PluginSettingGeneral", path: "../PluginSettingGeneral"),
        .package(name: "PluginStorage", path: "../PluginStorage"),
        .package(name: "PluginStore", path: "../PluginStore"),
        .package(name: "PluginThemeAurora", path: "../PluginThemeAurora"),
        .package(name: "PluginThemeCisum", path: "../PluginThemeCisum"),
        .package(name: "PluginThemeDaylightSilver", path: "../PluginThemeDaylightSilver"),
        .package(name: "PluginThemeForest", path: "../PluginThemeForest"),
        .package(name: "PluginThemeGraphiteBlack", path: "../PluginThemeGraphiteBlack"),
        .package(name: "PluginThemeMidnight", path: "../PluginThemeMidnight"),
        .package(name: "PluginThemeMono", path: "../PluginThemeMono"),
        .package(name: "PluginThemeNebula", path: "../PluginThemeNebula"),
        .package(name: "PluginThemeOcean", path: "../PluginThemeOcean"),
        .package(name: "PluginThemePaper", path: "../PluginThemePaper"),
        .package(name: "PluginThemeSettings", path: "../PluginThemeSettings"),
        .package(name: "PluginThemeStudioBlue", path: "../PluginThemeStudioBlue"),
        .package(name: "PluginThemeSunset", path: "../PluginThemeSunset"),
        .package(name: "PluginWelcome", path: "../PluginWelcome"),
    ],
    targets: [
            .target(
                name: "FactoryCisum",
            dependencies: [
                .product(name: "CisumKernel", package: "CisumKernel"),
                .product(name: "CisumUIComponents", package: "CisumUIComponents"),
                .product(name: "MagicKit", package: "MagicKit"),
                .product(name: "MagicPlayMan", package: "MagicPlayMan"),
                .product(name: "ProviderCloud", package: "ProviderCloud"),
                .product(name: "ProviderContentView", package: "ProviderContentView"),
                .product(name: "ProviderControlView", package: "ProviderControlView"),
                .product(name: "ProviderDevice", package: "ProviderDevice"),
                .product(name: "ProviderPlayback", package: "ProviderPlayback"),
                .product(name: "ProviderPlugin", package: "ProviderPlugin"),
                .product(name: "ProviderRootView", package: "ProviderRootView"),
                .product(name: "ProviderScene", package: "ProviderScene"),
                .product(name: "ProviderSettings", package: "ProviderSettings"),
                .product(name: "ProviderToolbar", package: "ProviderToolbar"),
                .product(name: "PluginAudio", package: "PluginAudio"),
                .product(name: "PluginAudioControl", package: "PluginAudioControl"),
                .product(name: "PluginAudioCopy", package: "PluginAudioCopy"),
                .product(name: "PluginAudioDBView", package: "PluginAudioDBView"),
                .product(name: "PluginAudioDemo", package: "PluginAudioDemo"),
                .product(name: "PluginAudioDownload", package: "PluginAudioDownload"),
                .product(name: "PluginAudioJob", package: "PluginAudioJob"),
                .product(name: "PluginAudioLike", package: "PluginAudioLike"),
                .product(name: "PluginAudioPlayMode", package: "PluginAudioPlayMode"),
                .product(name: "PluginAudioProgress", package: "PluginAudioProgress"),
                .product(name: "PluginAudioScene", package: "PluginAudioScene"),
                .product(name: "PluginAudioSettings", package: "PluginAudioSettings"),
                .product(name: "PluginAudioWidgetControl", package: "PluginAudioWidgetControl"),
                .product(name: "PluginBook", package: "PluginBook"),
                .product(name: "PluginBookControl", package: "PluginBookControl"),
                .product(name: "PluginBookDBView", package: "PluginBookDBView"),
                .product(name: "PluginBookLike", package: "PluginBookLike"),
                .product(name: "PluginBookPlayMode", package: "PluginBookPlayMode"),
                .product(name: "PluginBookProgress", package: "PluginBookProgress"),
                .product(name: "PluginBookScene", package: "PluginBookScene"),
                .product(name: "PluginBookSettings", package: "PluginBookSettings"),
                .product(name: "PluginFileLog", package: "PluginFileLog"),
                .product(name: "PluginLikeButton", package: "PluginLikeButton"),
                .product(name: "PluginOpenButton", package: "PluginOpenButton"),
                .product(name: "PluginPluginManager", package: "PluginPluginManager"),
                .product(name: "PluginReset", package: "PluginReset"),
                .product(name: "PluginScene", package: "PluginScene"),
                .product(name: "PluginSettingGeneral", package: "PluginSettingGeneral"),
                .product(name: "PluginStorage", package: "PluginStorage"),
                .product(name: "PluginStore", package: "PluginStore"),
                .product(name: "PluginThemeAurora", package: "PluginThemeAurora"),
                .product(name: "PluginThemeCisum", package: "PluginThemeCisum"),
                .product(name: "PluginThemeDaylightSilver", package: "PluginThemeDaylightSilver"),
                .product(name: "PluginThemeForest", package: "PluginThemeForest"),
                .product(name: "PluginThemeGraphiteBlack", package: "PluginThemeGraphiteBlack"),
                .product(name: "PluginThemeMidnight", package: "PluginThemeMidnight"),
                .product(name: "PluginThemeMono", package: "PluginThemeMono"),
                .product(name: "PluginThemeNebula", package: "PluginThemeNebula"),
                .product(name: "PluginThemeOcean", package: "PluginThemeOcean"),
                .product(name: "PluginThemePaper", package: "PluginThemePaper"),
                .product(name: "PluginThemeSettings", package: "PluginThemeSettings"),
                .product(name: "PluginThemeStudioBlue", package: "PluginThemeStudioBlue"),
                .product(name: "PluginThemeSunset", package: "PluginThemeSunset"),
                .product(name: "PluginWelcome", package: "PluginWelcome"),
            ],
            path: ".",
            sources: ["Sources/FactoryCisum"],
            resources: [
                .process("Resources"),
            ]
        ),
    ],
    swiftLanguageModes: [.v5]
)
