// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "CisumUI",
    platforms: [
        .macOS(.v14),
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "CisumUI",
            targets: ["CisumUI"]
        )
    ],
    dependencies: [
        .package(name: "MagicKit", path: "../MagicKit")
    ],
    targets: [
        .target(
            name: "CisumUI",
            dependencies: ["MagicKit"],
            path: "Sources/CisumUI",
            exclude: [
                "App",
                "App+Preview.swift",
                "AvatarView",
                "Background",
                "Button",
                "Card",
                "Conditional",
                "Container",
                "DateFormattingDemoView.swift",
                "Desktop",
                "Device",
                "DownloadMonitor",
                "Error",
                "ExtButton+Disabled.swift",
                "ExtButton+Interactive.swift",
                "ExtButton+Loading.swift",
                "ExtButton+Size.swift",
                "ExtButton+Style.swift",
                "ExtImage+App.swift",
                "ExtImage+BaseIcon.swift",
                "ExtImage+BookIcon.swift",
                "ExtImage+CameraIcon.swift",
                "ExtImage+CoffeeReelIcon.swift",
                "ExtImage+GlobeIcon.swift",
                "ExtImage+KidsEduIcon.swift",
                "ExtImage+MusicIcon.swift",
                "ExtImage+NoteIcon.swift",
                "ExtImage+PencilIcon.swift",
                "ExtImage+PlatformImage.swift",
                "ExtImage+Preview.swift",
                "ExtImage+Processing.swift",
                "ExtImage+VideoPlayerIcon.swift",
                "ExtNSImage.swift",
                "ExtString+Icon.swift",
                "ExtText.swift",
                "ExtView.swift",
                "ExtView+Background.swift",
                "ExtView+Button.swift",
                "ExtView+Card.swift",
                "ExtView+Centered.swift",
                "ExtView+Color.swift",
                "ExtView+Conditional.swift",
                "ExtView+Container.swift",
                "ExtView+DashedBorder.swift",
                "ExtView+Desktop.swift",
                "ExtView+Divider.swift",
                "ExtView+Gradient.swift",
                "ExtView+HStack.swift",
                "ExtView+Hover.swift",
                "ExtView+Infinity.swift",
                "ExtView+KeyValue.swift",
                "ExtView+Loading.swift",
                "ExtView+Mask.swift",
                "ExtView+Padding.swift",
                "ExtView+Poster.swift",
                "ExtView+Rounded.swift",
                "ExtView+Screen.swift",
                "ExtView+ScrollView.swift",
                "ExtView+Shadow.swift",
                "ExtView+Snapshot.swift",
                "ExtView+TextGradient.swift",
                "ExtView+VStack.swift",
                "Hover",
                "HttpClientPreview.swift",
                "Image",
                "IntExtensionDemoView.swift",
                "KeyValue",
                "Loading",
                "MagicAudioView.swift",
                "MagicErrorView.swift",
                "MagicFeature.swift",
                "MagicMediaPicker.swift",
                "MagicMenu.swift",
                "MagicProgressBar.swift",
                "MagicUserDefaultsView.swift",
                "Mask",
                "Open",
                "Padding",
                "Poster",
                "Rounded",
                "Setting",
                "Shadow",
                "Shell",
                "String",
                "Thumbnail",
                "TimeIntervalExtensionDemoView.swift",
                "Tooltip",
                "URL",
                "Utils",
                "VDemoSection.swift",
            ],
            sources: [
                "Components",
                "DesignSystem",
                "Plugin",
                "Support",
                "Theme",
            ],
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency=minimal"),
            ]
        ),
        .testTarget(
            name: "CisumUITests",
            dependencies: ["CisumUI"],
            path: "Tests/CisumUITests",
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency=minimal"),
            ]
        )
    ],
    swiftLanguageModes: [.v5]
)
