// swift-tools-version: 6.0
import PackageDescription

/// Manually maintained package definition for the Cisum plugin registry.
///
/// When adding or removing a plugin, update:
/// 1. The `dependencies` array below
/// 2. The `target.dependencies` array below
/// 3. The corresponding `import` and `plugins.append(...)` in `Sources/PluginRegistry.swift`

let package = Package(
    name: "PluginRegistry",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        .library(
            name: "PluginRegistry",
            targets: ["PluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../CisumUI"),
        .package(path: "../CisumFactory"),
        // MARK: - Plugin Dependencies (keep in sync with PluginRegistry.swift)
        .package(path: "../PluginAudio"),
        .package(path: "../PluginAudioControl"),
        .package(path: "../PluginAudioCopy"),
        .package(path: "../PluginAudioDBView"),
        .package(path: "../PluginAudioDemo"),
        .package(path: "../PluginAudioDownload"),
        .package(path: "../PluginAudioJob"),
        .package(path: "../PluginAudioLike"),
        .package(path: "../PluginAudioPlayMode"),
        .package(path: "../PluginAudioProgress"),
        .package(path: "../PluginAudioScene"),
        .package(path: "../PluginAudioSettings"),
        .package(path: "../PluginAudioWidgetControl"),
        .package(path: "../PluginBook"),
        .package(path: "../PluginBookControl"),
        .package(path: "../PluginBookDBView"),
        .package(path: "../PluginBookLike"),
        .package(path: "../PluginBookPlayMode"),
        .package(path: "../PluginBookProgress"),
        .package(path: "../PluginBookScene"),
        .package(path: "../PluginBookSettings"),
        .package(path: "../PluginFileLog"),
        .package(path: "../PluginLikeButton"),
        .package(path: "../PluginOpenButton"),
        .package(path: "../PluginReset"),
        .package(path: "../PluginSettingGeneral"),
        .package(path: "../PluginStorage"),
        .package(path: "../PluginStore"),
        .package(path: "../PluginThemeAurora"),
        .package(path: "../PluginThemeCisum"),
        .package(path: "../PluginThemeDaylightSilver"),
        .package(path: "../PluginThemeForest"),
        .package(path: "../PluginThemeGraphiteBlack"),
        .package(path: "../PluginThemeMidnight"),
        .package(path: "../PluginThemeMono"),
        .package(path: "../PluginThemeNebula"),
        .package(path: "../PluginThemeOcean"),
        .package(path: "../PluginThemePaper"),
        .package(path: "../PluginThemeSettings"),
        .package(path: "../PluginThemeStudioBlue"),
        .package(path: "../PluginThemeSunset"),
        .package(path: "../PluginWelcome"),
    ],
    targets: [
        .target(
            name: "PluginRegistry",
            dependencies: [
                "CisumUI",
                "CisumFactory",
                "PluginAudio",
                "PluginAudioControl",
                "PluginAudioCopy",
                "PluginAudioDBView",
                "PluginAudioDemo",
                "PluginAudioDownload",
                "PluginAudioJob",
                "PluginAudioLike",
                "PluginAudioPlayMode",
                "PluginAudioProgress",
                "PluginAudioScene",
                "PluginAudioSettings",
                "PluginAudioWidgetControl",
                "PluginBook",
                "PluginBookControl",
                "PluginBookDBView",
                "PluginBookLike",
                "PluginBookPlayMode",
                "PluginBookProgress",
                "PluginBookScene",
                "PluginBookSettings",
                "PluginFileLog",
                "PluginLikeButton",
                "PluginOpenButton",
                "PluginReset",
                "PluginSettingGeneral",
                "PluginStorage",
                "PluginStore",
                "PluginThemeAurora",
                "PluginThemeCisum",
                "PluginThemeDaylightSilver",
                "PluginThemeForest",
                "PluginThemeGraphiteBlack",
                "PluginThemeMidnight",
                "PluginThemeMono",
                "PluginThemeNebula",
                "PluginThemeOcean",
                "PluginThemePaper",
                "PluginThemeSettings",
                "PluginThemeStudioBlue",
                "PluginThemeSunset",
                "PluginWelcome",
            ],
            path: "Sources"
        ),
    ]
)
