#!/bin/sh
set -eu

ROOT_DIR="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PACKAGES_DIR="$ROOT_DIR/Packages"
OUTPUT="$ROOT_DIR/CisumApp/Core/Generated/GeneratedPluginRegistry.swift"
TMP_OUTPUT="$OUTPUT.tmp"

mkdir -p "$(dirname "$OUTPUT")"

package_entries=$(
    find "$PACKAGES_DIR" -mindepth 4 -maxdepth 4 -path "$PACKAGES_DIR/Plugin*/Sources/*/*.swift" -print |
    sort |
    while IFS= read -r plugin_file; do
        actor_name=$(sed -n 's/^[[:space:]]*public actor \([A-Za-z0-9_]*Plugin\):.*SuperPlugin.*/\1/p' "$plugin_file" | head -1)
        [ -n "$actor_name" ] || continue

        package_name=$(printf '%s\n' "$plugin_file" | sed "s#^$PACKAGES_DIR/##; s#/.*##")
        [ -n "$package_name" ] || continue

        platform_condition=""
        if grep -q '^#if os(macOS)' "$plugin_file"; then
            platform_condition="os(macOS)"
        fi

        printf '%s|%s|%s|package\n' "$actor_name" "$package_name" "$platform_condition"
    done
)
registry_entries=$(printf '%s\n' "$package_entries" | awk 'NF > 0' | sort -u)
registry_imports=$(printf '%s\n' "$registry_entries" | awk -F'|' '{ print $2 }' | sort -u)

{
    printf '// This file is generated by Scripts/generate_plugin_registry.sh.\n'
    printf '// Do not edit by hand.\n\n'
    printf 'import CisumUI\n'
    printf '%s\n' "$registry_imports" |
    while IFS= read -r package_name; do
        [ -n "$package_name" ] || continue
        printf 'import %s\n' "$package_name"
    done
    printf '\n'
    printf 'enum GeneratedPluginRegistry {\n'
    printf '    @MainActor\n'
    printf '    static var plugins: [any SuperPlugin] {\n'
        printf '        var plugins: [any SuperPlugin] = []\n'
    printf '%s\n' "$registry_entries" |
    while IFS='|' read -r actor_name package_name platform_condition source; do
        [ -n "$actor_name" ] || continue
        if [ -n "$platform_condition" ]; then
            printf '        #if %s\n' "$platform_condition"
            printf '            plugins.append(%s.shared) // %s\n' "$actor_name" "$package_name"
            printf '        #endif\n'
        else
            printf '        plugins.append(%s.shared) // %s\n' "$actor_name" "$package_name"
        fi
    done
    printf '        return plugins\n'
    printf '    }\n'
    printf '}\n'
} > "$TMP_OUTPUT"

if [ -f "$OUTPUT" ] && cmp -s "$TMP_OUTPUT" "$OUTPUT"; then
    rm "$TMP_OUTPUT"
else
    mv "$TMP_OUTPUT" "$OUTPUT"
fi
