name: Release

on:
  push:
    tags:
      - '*'
  # workflow_run:
  #   workflows:
  #     - 'Bump'
  #   types:
  #     - completed

permissions:
  contents: write

env:
  tag: '-'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - name: Generate Changelog
        run: echo 'macOS、iOS版本在这里：[前往App Store](https://apps.apple.com/cn/app/cisum/id6466401036)'> ${{ github.workspace }}-CHANGELOG.txt
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            ./**/*.dmg
            ./**/*.zip
            ./**/*.exe
            ./**/*.pkg
            ./**/*.deb
            ./**/*.ipa
            ./**/*.AppImage
            ./**/*.snap
