// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "CisumPluginRegistry",
    platforms: [
        .macOS(.v15),
        .iOS(.v18),
    ],
    products: [
        .library(
            name: "CisumPluginRegistry",
            targets: ["CisumPluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../CisumUI"),
        .package(path: "../../Plugins/PluginAudio"),
        .package(path: "../../Plugins/PluginAudioControl"),
        .package(path: "../../Plugins/PluginAudioCopy"),
        .package(path: "../../Plugins/PluginAudioDBView"),
        .package(path: "../../Plugins/PluginAudioDemo"),
        .package(path: "../../Plugins/PluginAudioDownload"),
        .package(path: "../../Plugins/PluginAudioJob"),
        .package(path: "../../Plugins/PluginAudioLike"),
        .package(path: "../../Plugins/PluginAudioPlayMode"),
        .package(path: "../../Plugins/PluginAudioProgress"),
        .package(path: "../../Plugins/PluginAudioScene"),
        .package(path: "../../Plugins/PluginAudioSettings"),
        .package(path: "../../Plugins/PluginAudioWidgetControl"),
        .package(path: "../../Plugins/PluginBook"),
        .package(path: "../../Plugins/PluginBookControl"),
        .package(path: "../../Plugins/PluginBookDBView"),
        .package(path: "../../Plugins/PluginBookLike"),
        .package(path: "../../Plugins/PluginBookPlayMode"),
        .package(path: "../../Plugins/PluginBookProgress"),
        .package(path: "../../Plugins/PluginBookScene"),
        .package(path: "../../Plugins/PluginBookSettings"),
        .package(path: "../../Plugins/PluginFileLog"),
        .package(path: "../../Plugins/PluginLikeButton"),
        .package(path: "../../Plugins/PluginOpenButton"),
        .package(path: "../../Plugins/PluginReset"),
        .package(path: "../../Plugins/PluginStorage"),
        .package(path: "../../Plugins/PluginStore"),
        .package(path: "../../Plugins/PluginThemeAurora"),
        .package(path: "../../Plugins/PluginThemeCisum"),
        .package(path: "../../Plugins/PluginThemeDaylightSilver"),
        .package(path: "../../Plugins/PluginThemeForest"),
        .package(path: "../../Plugins/PluginThemeGraphiteBlack"),
        .package(path: "../../Plugins/PluginThemeMidnight"),
        .package(path: "../../Plugins/PluginThemeMono"),
        .package(path: "../../Plugins/PluginThemeNebula"),
        .package(path: "../../Plugins/PluginThemeOcean"),
        .package(path: "../../Plugins/PluginThemePaper"),
        .package(path: "../../Plugins/PluginThemeSettings"),
        .package(path: "../../Plugins/PluginThemeStudioBlue"),
        .package(path: "../../Plugins/PluginThemeSunset"),
        .package(path: "../../Plugins/PluginWelcome"),
    ],
    targets: [
        .target(
            name: "CisumPluginRegistry",
            dependencies: [
                "CisumUI",
                "PluginAudio",
                "PluginAudioControl",
                "PluginAudioCopy",
                "PluginAudioDBView",
                "PluginAudioDemo",
                "PluginAudioDownload",
                "PluginAudioJob",
                "PluginAudioLike",
                "PluginAudioPlayMode",
                "PluginAudioProgress",
                "PluginAudioScene",
                "PluginAudioSettings",
                "PluginAudioWidgetControl",
                "PluginBook",
                "PluginBookControl",
                "PluginBookDBView",
                "PluginBookLike",
                "PluginBookPlayMode",
                "PluginBookProgress",
                "PluginBookScene",
                "PluginBookSettings",
                "PluginFileLog",
                "PluginLikeButton",
                "PluginOpenButton",
                "PluginReset",
                "PluginStorage",
                "PluginStore",
                "PluginThemeAurora",
                "PluginThemeCisum",
                "PluginThemeDaylightSilver",
                "PluginThemeForest",
                "PluginThemeGraphiteBlack",
                "PluginThemeMidnight",
                "PluginThemeMono",
                "PluginThemeNebula",
                "PluginThemeOcean",
                "PluginThemePaper",
                "PluginThemeSettings",
                "PluginThemeStudioBlue",
                "PluginThemeSunset",
                "PluginWelcome",
            ],
            path: "Sources/CisumPluginRegistry"
        ),
    ]
)
