// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "CisumPluginRegistry",
    platforms: [
        .macOS(.v15),
        .iOS(.v18),
    ],
    products: [
        .library(
            name: "CisumPluginRegistry",
            targets: ["CisumPluginRegistry"]
        ),
    ],
    dependencies: [
        .package(path: "../CisumUI"),
        .package(path: "../../Plugins/AudioPlugin"),
        .package(path: "../../Plugins/AudioControlPlugin"),
        .package(path: "../../Plugins/AudioCopyPlugin"),
        .package(path: "../../Plugins/AudioDBViewPlugin"),
        .package(path: "../../Plugins/AudioDemoPlugin"),
        .package(path: "../../Plugins/AudioDownloadPlugin"),
        .package(path: "../../Plugins/AudioJobPlugin"),
        .package(path: "../../Plugins/AudioLikePlugin"),
        .package(path: "../../Plugins/AudioPlayModePlugin"),
        .package(path: "../../Plugins/AudioProgressPlugin"),
        .package(path: "../../Plugins/AudioScenePlugin"),
        .package(path: "../../Plugins/AudioSettingsPlugin"),
        .package(path: "../../Plugins/AudioWidgetControlPlugin"),
        .package(path: "../../Plugins/BookPlugin"),
        .package(path: "../../Plugins/BookControlPlugin"),
        .package(path: "../../Plugins/BookDBViewPlugin"),
        .package(path: "../../Plugins/BookLikePlugin"),
        .package(path: "../../Plugins/BookPlayModePlugin"),
        .package(path: "../../Plugins/BookProgressPlugin"),
        .package(path: "../../Plugins/BookScenePlugin"),
        .package(path: "../../Plugins/BookSettingsPlugin"),
        .package(path: "../../Plugins/FileLogPlugin"),
        .package(path: "../../Plugins/LikeButtonPlugin"),
        .package(path: "../../Plugins/OpenButtonPlugin"),
        .package(path: "../../Plugins/ResetPlugin"),
        .package(path: "../../Plugins/StoragePlugin"),
        .package(path: "../../Plugins/StorePlugin"),
        .package(path: "../../Plugins/ThemeAuroraPlugin"),
        .package(path: "../../Plugins/ThemeCisumPlugin"),
        .package(path: "../../Plugins/ThemeDaylightSilverPlugin"),
        .package(path: "../../Plugins/ThemeForestPlugin"),
        .package(path: "../../Plugins/ThemeGraphiteBlackPlugin"),
        .package(path: "../../Plugins/ThemeMidnightPlugin"),
        .package(path: "../../Plugins/ThemeMonoPlugin"),
        .package(path: "../../Plugins/ThemeNebulaPlugin"),
        .package(path: "../../Plugins/ThemeOceanPlugin"),
        .package(path: "../../Plugins/ThemePaperPlugin"),
        .package(path: "../../Plugins/ThemeSettingsPlugin"),
        .package(path: "../../Plugins/ThemeStudioBluePlugin"),
        .package(path: "../../Plugins/ThemeSunsetPlugin"),
        .package(path: "../../Plugins/WelcomePlugin"),
    ],
    targets: [
        .target(
            name: "CisumPluginRegistry",
            dependencies: [
                "CisumUI",
                "AudioPlugin",
                "AudioControlPlugin",
                "AudioCopyPlugin",
                "AudioDBViewPlugin",
                "AudioDemoPlugin",
                "AudioDownloadPlugin",
                "AudioJobPlugin",
                "AudioLikePlugin",
                "AudioPlayModePlugin",
                "AudioProgressPlugin",
                "AudioScenePlugin",
                "AudioSettingsPlugin",
                "AudioWidgetControlPlugin",
                "BookPlugin",
                "BookControlPlugin",
                "BookDBViewPlugin",
                "BookLikePlugin",
                "BookPlayModePlugin",
                "BookProgressPlugin",
                "BookScenePlugin",
                "BookSettingsPlugin",
                "FileLogPlugin",
                "LikeButtonPlugin",
                "OpenButtonPlugin",
                "ResetPlugin",
                "StoragePlugin",
                "StorePlugin",
                "ThemeAuroraPlugin",
                "ThemeCisumPlugin",
                "ThemeDaylightSilverPlugin",
                "ThemeForestPlugin",
                "ThemeGraphiteBlackPlugin",
                "ThemeMidnightPlugin",
                "ThemeMonoPlugin",
                "ThemeNebulaPlugin",
                "ThemeOceanPlugin",
                "ThemePaperPlugin",
                "ThemeSettingsPlugin",
                "ThemeStudioBluePlugin",
                "ThemeSunsetPlugin",
                "WelcomePlugin",
            ],
            path: "Sources"
        ),
    ]
)
